// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA0uX7Isd9Ptc3GZLDa0jS42lljtDVrV4',
    appId: '1:423082861401:web:ff422ce42c3ffe4f2e2248',
    messagingSenderId: '423082861401',
    projectId: 'captura-c859a',
    authDomain: 'captura-c859a.firebaseapp.com',
    storageBucket: 'captura-c859a.appspot.com',
    measurementId: 'G-RLMPJX5ET4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfboU3jM3lJM-0jJb2_Ks44_i_WFU7IqI',
    appId: '1:423082861401:android:dde6e1ba2e0f3e182e2248',
    messagingSenderId: '423082861401',
    projectId: 'captura-c859a',
    storageBucket: 'captura-c859a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNxFeGQfhMsHGHJvU8ZzTwJ6F5sZDu7Os',
    appId: '1:423082861401:ios:85a80508939a8f4c2e2248',
    messagingSenderId: '423082861401',
    projectId: 'captura-c859a',
    storageBucket: 'captura-c859a.appspot.com',
    androidClientId: '423082861401-fdbqeqi1d845cr9vmenfhkslvusbbut8.apps.googleusercontent.com',
    iosClientId: '423082861401-fs9us6ejpv168v1vl3itkqs9fn26qkto.apps.googleusercontent.com',
    iosBundleId: 'com.example.capturaLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNxFeGQfhMsHGHJvU8ZzTwJ6F5sZDu7Os',
    appId: '1:423082861401:ios:0a36b19b6b80f0972e2248',
    messagingSenderId: '423082861401',
    projectId: 'captura-c859a',
    storageBucket: 'captura-c859a.appspot.com',
    androidClientId: '423082861401-fdbqeqi1d845cr9vmenfhkslvusbbut8.apps.googleusercontent.com',
    iosClientId: '423082861401-r5c265bkjc9urisec7ef90sh7rdmoj6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.capturaLens.RunnerTests',
  );
}
